name: Trigger auto deployment for poc-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'Pandoc./**'
    - '.github/workflows/poc-container-AutoDeployTrigger-00e28b03-1688-4c32-af1e-3f1d95400a9e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: poccontainerdotnetapp20230508144740.azurecr.io
          username: ${{ secrets.POCCONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.POCCONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: poccontainerdotnetapp20230508144740.azurecr.io/poc-container:${{ github.sha }}
          file: Pandoc./Dockerfile
          context: Pandoc./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.POCCONTAINER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n poc-container -g CoE-Training --server poccontainerdotnetapp20230508144740.azurecr.io --username  ${{ secrets.POCCONTAINER_REGISTRY_USERNAME }} --password ${{ secrets.POCCONTAINER_REGISTRY_PASSWORD }}
            az containerapp update -n poc-container -g CoE-Training --image poccontainerdotnetapp20230508144740.azurecr.io/poc-container:${{ github.sha }}
